nacos:
  host: '10.102.109.196'
  # host: '10.102.213.148'
  port: 8848
  namespace: '0c56dfe6-d4a7-42ba-b2be-9502f91ece03'
  user: 'nacos'
  password: 'nacos'
  dataid: 'user-srv-dev.yaml'
  group: 'dev'
  timeoutms: 5000
  cachedir: 'tmp/nacos/cache'
  logdir: 'tmp/nacos/log'
  loglevel: 'debug'
