nacos:
  host: '10.102.109.196'
  port: 8848
  namespace: '2bcef975-5415-46ab-b7d7-fdabcd634e58'
  user: 'nacos'
  password: 'nacos'
  dataid: 'ticketorder-web-dev.yaml'
  group: 'dev'
  timeoutms: 5000
  cachedir: 'tmp/nacos/cache'
  logdir: 'tmp/nacos/log'
  loglevel: 'debug'
