// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDailyTrainSeat = "daily_train_seat"

// DailyTrainSeat mapped from table <daily_train_seat>
type DailyTrainSeat struct {
	ID                int64     `gorm:"column:id;primaryKey;comment:id" json:"id"`                                    // id
	Date              time.Time `gorm:"column:date;not null;comment:日期" json:"date"`                                  // 日期
	TrainCode         string    `gorm:"column:train_code;not null;comment:车次编号" json:"train_code"`                    // 车次编号
	CarriageIndex     int32     `gorm:"column:carriage_index;not null;comment:箱序" json:"carriage_index"`              // 箱序
	Row_              string    `gorm:"column:row;not null;comment:排号|01, 02" json:"row"`                             // 排号|01, 02
	Col               string    `gorm:"column:col;not null;comment:列号|枚举[SeatColEnum]" json:"col"`                    // 列号|枚举[SeatColEnum]
	SeatType          string    `gorm:"column:seat_type;not null;comment:座位类型|枚举[SeatTypeEnum]" json:"seat_type"`     // 座位类型|枚举[SeatTypeEnum]
	CarriageSeatIndex int32     `gorm:"column:carriage_seat_index;not null;comment:同车箱座序" json:"carriage_seat_index"` // 同车箱座序
	Sell              int64     `gorm:"column:sell;not null;comment:售卖情况|0表示可卖，1表示已卖" json:"sell"`                    // 售卖情况|0表示可卖，1表示已卖
	CreateTime        time.Time `gorm:"column:create_time;comment:新增时间" json:"create_time"`                           // 新增时间
	UpdateTime        time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`                           // 修改时间
}

// TableName DailyTrainSeat's table name
func (*DailyTrainSeat) TableName() string {
	return TableNameDailyTrainSeat
}
