// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDailyTrainCarriage = "daily_train_carriage"

// DailyTrainCarriage mapped from table <daily_train_carriage>
type DailyTrainCarriage struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:id" json:"id"`                                // id
	Date       time.Time `gorm:"column:date;not null;comment:日期" json:"date"`                              // 日期
	TrainCode  string    `gorm:"column:train_code;not null;comment:车次编号" json:"train_code"`                // 车次编号
	Index      int32     `gorm:"column:index;not null;comment:箱序" json:"index"`                            // 箱序
	SeatType   string    `gorm:"column:seat_type;not null;comment:座位类型|枚举[SeatTypeEnum]" json:"seat_type"` // 座位类型|枚举[SeatTypeEnum]
	SeatCount  int32     `gorm:"column:seat_count;not null;comment:座位数" json:"seat_count"`                 // 座位数
	RowCount   int32     `gorm:"column:row_count;not null;comment:排数" json:"row_count"`                    // 排数
	ColCount   int32     `gorm:"column:col_count;not null;comment:列数" json:"col_count"`                    // 列数
	CreateTime time.Time `gorm:"column:create_time;comment:新增时间" json:"create_time"`                       // 新增时间
	UpdateTime time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`                       // 修改时间
}

// TableName DailyTrainCarriage's table name
func (*DailyTrainCarriage) TableName() string {
	return TableNameDailyTrainCarriage
}
