// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStation = "station"

// Station mapped from table <station>
type Station struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:id" json:"id"`                   // id
	Name       string    `gorm:"column:name;not null;comment:站名" json:"name"`                 // 站名
	NamePinyin string    `gorm:"column:name_pinyin;not null;comment:站名拼音" json:"name_pinyin"` // 站名拼音
	NamePy     string    `gorm:"column:name_py;not null;comment:站名拼音首字母" json:"name_py"`      // 站名拼音首字母
	CreateTime time.Time `gorm:"column:create_time;comment:新增时间" json:"create_time"`          // 新增时间
	UpdateTime time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`          // 修改时间
}

// TableName Station's table name
func (*Station) TableName() string {
	return TableNameStation
}
