// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTrainSeat = "train_seat"

// TrainSeat mapped from table <train_seat>
type TrainSeat struct {
	ID                int64     `gorm:"column:id;primaryKey;comment:id" json:"id"`                                    // id
	TrainCode         string    `gorm:"column:train_code;not null;comment:车次编号" json:"train_code"`                    // 车次编号
	CarriageIndex     int32     `gorm:"column:carriage_index;not null;comment:厢序" json:"carriage_index"`              // 厢序
	Row_              string    `gorm:"column:row;not null;comment:排号|01, 02" json:"row"`                             // 排号|01, 02
	Col               string    `gorm:"column:col;not null;comment:列号|枚举[SeatColEnum]" json:"col"`                    // 列号|枚举[SeatColEnum]
	SeatType          string    `gorm:"column:seat_type;not null;comment:座位类型|枚举[SeatTypeEnum]" json:"seat_type"`     // 座位类型|枚举[SeatTypeEnum]
	CarriageSeatIndex int32     `gorm:"column:carriage_seat_index;not null;comment:同车厢座序" json:"carriage_seat_index"` // 同车厢座序
	CreateTime        time.Time `gorm:"column:create_time;comment:新增时间" json:"create_time"`                           // 新增时间
	UpdateTime        time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`                           // 修改时间
}

// TableName TrainSeat's table name
func (*TrainSeat) TableName() string {
	return TableNameTrainSeat
}
