nacos:
  host: '10.102.109.196'
  port: 8848
  namespace: '018782e9-4d17-42a6-a34e-82663dccc547'
  user: 'nacos'
  password: 'nacos'
  dataid: 'user-web-dev.yaml'
  group: 'dev'
  timeoutms: 5000
  cachedir: 'tmp/nacos/cache'
  logdir: 'tmp/nacos/log'
  loglevel: 'debug'
